name: Semgrep Security Scan

on: [push, pull_request]

jobs:
  semgrep-scan:
    name: Run Semgrep Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          semgrep --version
      
      - name: Run Semgrep Scan with PHP Rules
        run: |
          semgrep --config=p/php --sarif --output=semgrep-results.sarif --error
      
      - name: Upload SARIF Results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
