name: Semgrep Security Scan

on: [push, pull_request]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          semgrep --version

      - name: Run Semgrep Scan (SARIF & JSON)
        run: |
          semgrep --config=p/php --sarif --output=semgrep-results.sarif
          semgrep --config=p/php --json --output=semgrep-results.json

      - name: Upload SARIF results (for GitHub Code Scanning)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

      - name: Upload Semgrep JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: semgrep-results.json
          if-no-files-found: ignore

